services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://backend:5000
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #   ports:
  #     - "5000:5000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - azurite
  #   command: sh -c "python -m database.db_setup && python main.py"

  # db:
  #   image: postgres:17-alpine
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: config_tool_db
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"  # Queue service (optional)
      - "10002:10002"  # Table service (optional)
    command: "azurite-blob --blobHost 0.0.0.0 --loose --disableTelemetry"



# volumes:
#   pgdata: