grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
    n_jobs: -1

model_selection:
  module_0:
    class: CatBoostClassifier
    module: catboost
    params:
      iterations: 100
      learning_rate: 0.1
      depth: 6
      verbose: 0
    search_param_grid:
      iterations:
      - 100
      - 200
      - 300
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      depth:
      - 4
      - 6
      - 8

  module_1:
    class: XGBClassifier
    module: xgboost
    params:
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 100
      verbosity: 0
      objective: binary:logistic
    search_param_grid:
      max_depth:
      - 4
      - 6
      - 8
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      n_estimators:
      - 50
      - 100
      - 150


# grid_search:
#   class: GridSearchCV
#   module: sklearn.model_selection
#   params:
#     cv: 3
#     verbose: 3
# model_selection:
#   module_0:
#     class: KNeighborsClassifier
#     module: sklearn.neighbors
#     params:
#       algorithm: kd_tree
#       weights: uniform
#       n_neighbors: 3
#     search_param_grid:
#       algorithm:
#       - auto
#       - ball_tree
#       - kd_tree
#       - brute
#       weights:
#       - uniform
#       - distance
#       n_neighbors:
#       - 3
#       - 5
#       - 9

      
#   module_1:
#     class: RandomForestClassifier
#     module: sklearn.ensemble
#     params:
#       max_depth: 10
#       max_features: sqrt
#       n_estimators: 3
#     search_param_grid:
#       max_depth:
#       - 10
#       - 15
#       - 20
#       max_features:
#       - sqrt
#       - log2
#       n_estimators:
#       - 3
#       - 5
#       - 9